// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aritcles.sql

package database

import (
	"context"
)

const createAritcle = `-- name: CreateAritcle :one
INSERT INTO articles(id,author,article_text, created_at,updated_at, published_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    NOW()
)

RETURNING id, author, article_text, published_at, created_at, updated_at
`

type CreateAritcleParams struct {
	Author      string
	ArticleText string
}

func (q *Queries) CreateAritcle(ctx context.Context, arg CreateAritcleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createAritcle, arg.Author, arg.ArticleText)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.ArticleText,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, author, article_text, published_at, created_at, updated_at FROM articles
`

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.ArticleText,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
