// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Article struct {
	ID          uuid.UUID
	Author      string
	ArticleText string
	PublishedAt sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Tag struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Tagsarticle struct {
	ID        uuid.UUID
	AritcleID uuid.UUID
	TagID     uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
