// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotes.sql

package database

import (
	"context"
)

const createQoute = `-- name: CreateQoute :one
INSERT INTO quotes(id,author,qoute_text, created_at,updated_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW()
)

RETURNING id, author, qoute_text, created_at, updated_at
`

type CreateQouteParams struct {
	Author    string
	QouteText string
}

func (q *Queries) CreateQoute(ctx context.Context, arg CreateQouteParams) (Quote, error) {
	row := q.db.QueryRowContext(ctx, createQoute, arg.Author, arg.QouteText)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.QouteText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, author, qoute_text, created_at, updated_at FROM quotes
`

func (q *Queries) ListQuotes(ctx context.Context) ([]Quote, error) {
	rows, err := q.db.QueryContext(ctx, listQuotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.QouteText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
