// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package database

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    now(),
    now()
)

RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
