// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags_articles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addTagToArticle = `-- name: AddTagToArticle :one
INSERT INTO tagsArticles (id ,aritcle_id, tag_id, created_at, updated_at) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    now(),
    now()
)

RETURNING id, aritcle_id, tag_id, created_at, updated_at
`

type AddTagToArticleParams struct {
	AritcleID uuid.UUID
	TagID     uuid.UUID
}

func (q *Queries) AddTagToArticle(ctx context.Context, arg AddTagToArticleParams) (Tagsarticle, error) {
	row := q.db.QueryRowContext(ctx, addTagToArticle, arg.AritcleID, arg.TagID)
	var i Tagsarticle
	err := row.Scan(
		&i.ID,
		&i.AritcleID,
		&i.TagID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
