// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AppBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"bg-white dark:bg-slate-950 font-['Manrope'] antialiased tracking-tight docked full-width top-0 border-b border-slate-100 dark:border-slate-900 flat no shadows fixed w-full z-50\"><div class=\"flex justify-between items-center w-full px-8 py-6 max-w-4xl mx-auto\"><span class=\"text-lg font-bold text-[#002B5B] dark:text-slate-100 tracking-widest uppercase\">github.com/PhoenixTech2003/go-blog</span><nav class=\"hidden md:flex items-center space-x-8\"><a class=\"text-[#002B5B] dark:text-white font-semibold hover:text-[#002B5B] dark:hover:text-white transition-colors duration-200 active:opacity-70\" href=\"/\">Library</a> <a class=\"text-slate-400 dark:text-slate-600 hover:text-[#002B5B] dark:hover:text-white transition-colors duration-200 active:opacity-70\" href=\"/compose\">Compose</a></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
