// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AppBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"sticky top-0 z-50 flex justify-between items-center w-full px-margin-mobile md:px-gutter py-4 bg-surface border-b border-outline-variant max-w-container-max mx-auto\"><div class=\"flex items-center gap-8\"><a class=\"font-display-lg text-headline-sm font-bold text-primary\" href=\"/\">Minimalist</a><div class=\"hidden md:flex gap-6 items-center\"><a class=\"text-primary font-bold border-b-2 border-primary pb-1 type-label-md\" href=\"/\">Library</a> <a class=\"text-on-surface-variant type-label-md hover:text-primary transition-colors\" href=\"/compose\">Compose</a></div></div><div class=\"flex items-center gap-4\"><a class=\"bg-primary text-on-primary px-4 py-2 rounded font-label-md text-label-md hover:opacity-80 transition-opacity flex items-center gap-2\" href=\"/compose\"><span class=\"material-symbols-outlined text-[18px]\">add</span> New Post</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
