// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ComposeForm(formSubmissionSuccessful *bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"compose\" class=\"space-y-stack-lg\" data-on:submit=\"@post('/compose/qoutes/', {contentType: 'form'})\" data-indicator:_composePosting><!-- Quote Text Area --><div class=\"group transition-all duration-300\"><label class=\"type-label-sm text-outline mb-unit block uppercase\" for=\"qoute\">Quote Text</label> <textarea id=\"qoute\" name=\"qoute\" class=\"w-full bg-transparent border-0 border-b border-outline-variant focus:ring-0 focus:border-secondary type-display-lg placeholder:text-surface-container-highest resize-none py-stack-sm transition-all px-0\" placeholder=\"Begin typing the words that resonated...\" rows=\"4\"></textarea></div><!-- Author Input Area --><div class=\"group transition-all duration-300\"><label class=\"type-label-sm text-outline mb-unit block uppercase\" for=\"author\">Author Name</label><div class=\"flex items-center gap-unit border-b border-outline-variant focus-within:border-secondary py-stack-sm\"><span class=\"text-outline-variant type-label-sm\">—</span> <input id=\"author\" name=\"author\" class=\"w-full bg-transparent border-0 focus:ring-0 type-headline-sm placeholder:text-surface-container-highest transition-all px-0\" placeholder=\"Identify the thinker\" type=\"text\"></div></div><!-- Action Button --><div class=\"pt-stack-md flex justify-center md:justify-start\"><button class=\"bg-primary text-on-primary hover:opacity-80 transition-all duration-300 px-12 py-4 rounded active:scale-95 flex items-center gap-unit group\" type=\"submit\"><span class=\"type-label-sm uppercase tracking-widest\">Add Quote</span> <span class=\"material-symbols-outlined text-lg group-hover:translate-x-1 transition-transform\" data-icon=\"arrow_forward\">arrow_forward</span></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if formSubmissionSuccessful != nil && *formSubmissionSuccessful == false {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"text-error\">Failed to Create qoute</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if formSubmissionSuccessful != nil && *formSubmissionSuccessful == true {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<p class=\"text-secondary\">Qoute added successfully</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
