// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SmallListItemSection() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"md:col-span-12 grid grid-cols-1 md:grid-cols-3 gap-8 pt-8 border-t border-outline-variant\"><article class=\"group cursor-pointer\"><div class=\"space-y-3\"><div class=\"flex items-center gap-4\"><span class=\"font-label-sm text-label-sm text-secondary uppercase tracking-widest\">Life</span> <span class=\"font-label-sm text-label-sm text-on-surface-variant\">Oct 20, 2024</span></div><h3 class=\"font-headline-sm text-headline-sm group-hover:text-secondary transition-colors\">Living with Less: A Year of Intentionality</h3><p class=\"font-body-md text-body-md text-on-surface-variant\">Personal reflections on the first twelve months of living with fewer than 100 essential possessions.</p></div></article><article class=\"group cursor-pointer\"><div class=\"space-y-3\"><div class=\"flex items-center gap-4\"><span class=\"font-label-sm text-label-sm text-secondary uppercase tracking-widest\">Design</span> <span class=\"font-label-sm text-label-sm text-on-surface-variant\">Oct 18, 2024</span></div><h3 class=\"font-headline-sm text-headline-sm group-hover:text-secondary transition-colors\">Typography as Voice</h3><p class=\"font-body-md text-body-md text-on-surface-variant\">How the weight and rhythm of a typeface dictates the internal monologue of the reader.</p></div></article><article class=\"group cursor-pointer\"><div class=\"space-y-3\"><div class=\"flex items-center gap-4\"><span class=\"font-label-sm text-label-sm text-secondary uppercase tracking-widest\">Tech</span> <span class=\"font-label-sm text-label-sm text-on-surface-variant\">Oct 15, 2024</span></div><h3 class=\"font-headline-sm text-headline-sm group-hover:text-secondary transition-colors\">The Slow Web Manifesto</h3><p class=\"font-body-md text-body-md text-on-surface-variant\">Proposing a shift from algorithmic speed to human-paced discovery on the internet.</p></div></article></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
