// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SortFilterHeader() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12\"><div class=\"space-y-4\"><h1 class=\"font-headline-md text-headline-md text-primary\">The Reading List</h1><div class=\"flex flex-wrap gap-2\"><button class=\"px-4 py-1.5 bg-primary text-on-primary rounded-full font-label-sm text-label-sm\">All</button> <button class=\"px-4 py-1.5 bg-surface-container-low text-on-surface-variant rounded-full font-label-sm text-label-sm hover:bg-surface-container-high transition-colors\">Design</button> <button class=\"px-4 py-1.5 bg-surface-container-low text-on-surface-variant rounded-full font-label-sm text-label-sm hover:bg-surface-container-high transition-colors\">Tech</button> <button class=\"px-4 py-1.5 bg-surface-container-low text-on-surface-variant rounded-full font-label-sm text-label-sm hover:bg-surface-container-high transition-colors\">Life</button></div></div><div class=\"relative group\"><button class=\"flex items-center gap-2 px-4 py-2 border border-outline-variant rounded-DEFAULT font-label-md text-label-md text-on-surface-variant hover:border-primary transition-colors\">Sort by Date <span class=\"material-symbols-outlined text-[18px]\">expand_more</span></button></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
