// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package index

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FeaturedCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article class=\"md:col-span-8 group cursor-pointer\"><div class=\"aspect-[16/9] overflow-hidden mb-6 rounded-lg bg-surface-variant\"><img alt=\"Minimalist Workspace\" class=\"w-full h-full object-cover transition-transform duration-700 group-hover:scale-105\" data-alt=\"A clean, minimalist workspace featuring a white desk, a single designer lamp, and a small notebook. The lighting is soft and natural, coming from a large window out of frame. The composition is spacious and airy, emphasizing a quiet editorial aesthetic with a palette of soft whites and warm grays.\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuDpm-bgBiNwGjJbfIe0oOfnap5Tyw96rl0CRwkb3cPSa2aFnltbWUQlcWqNYDkV9QerZtdndECkLLcuUzo_yHBFN-5uAJF5vbEg_bOetCv7glOJ-fSRYH0i1Qy-pbo2_8L90K-SXHvBk4UnAQH2NED2StAHYPOcZt4DsQiDQi4-PTGFofmzUqnZlgRynuTZ9Qcg9U9HpMWvHNvmONK7JFBv49Yt03eKEI9uNMS9tJF5qsw5QqZ-RZSu0rCsqgw5pFEOu1KTd87X\"></div><div class=\"space-y-3\"><div class=\"flex items-center gap-4\"><span class=\"font-label-sm text-label-sm text-secondary uppercase tracking-widest\">Design</span> <span class=\"font-label-sm text-label-sm text-on-surface-variant\">Oct 24, 2024</span></div><h2 class=\"font-headline-md text-headline-md group-hover:text-secondary transition-colors leading-tight\">The Art of Negative Space in Modern Digital Interfaces</h2><p class=\"font-body-md text-body-md text-on-surface-variant line-clamp-2 max-w-2xl\">Understanding how silence and void in design can amplify the impact of content and provide a focused sanctuary for the reader's attention.</p></div></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
