// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package index

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SecondaryCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article class=\"md:col-span-4 group cursor-pointer\"><div class=\"aspect-square overflow-hidden mb-6 rounded-lg bg-surface-variant\"><img alt=\"Tech Evolution\" class=\"w-full h-full object-cover transition-transform duration-700 group-hover:scale-105\" data-alt=\"An assortment of vintage and modern technology hardware arranged neatly on a matte black surface. A classic mechanical keyboard sits next to a sleek modern tablet. The lighting is low-key with high-contrast shadows, creating a sophisticated and intellectual mood using a monochrome color scheme.\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBe3tsK9XNrc9wdeliJyJpElC_n1PAFG8pogrbHauvpRSWDnto0vgremLvalBmlTklkNgPFV7JfxE7k5N4YOPWydA1G-pBXPJHceWCrnefLpqTfuk8kng3impflpjpk_H5tE14J2NbnASiZL54C9Xpkcs2dXSL846zgL3jIjhi_ED76hHP7Vj2_SB6-FHfAdY-usGHiGyMchhMYQ0crPqtLv9l3oYPnIpvXVw65-oK0gL6Nd1Y2TZz0qmmt5YUkzDXCKHTq4Z1b\"></div><div class=\"space-y-3\"><div class=\"flex items-center gap-4\"><span class=\"font-label-sm text-label-sm text-secondary uppercase tracking-widest\">Tech</span> <span class=\"font-label-sm text-label-sm text-on-surface-variant\">Oct 22, 2024</span></div><h3 class=\"font-headline-sm text-headline-sm group-hover:text-secondary transition-colors\">Hardware for the Focused Mind</h3><p class=\"font-body-md text-body-md text-on-surface-variant line-clamp-3\">Evaluating the tools that prioritize utility over distraction in an age of constant connectivity.</p></div></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
