// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/api/articles": {
            "post": {
                "description": "This endpoint is used to create a new article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "Creates a new blog article",
                "parameters": [
                    {
                        "description": "Article Data",
                        "name": "qoute",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.articleRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Article Created Succefully",
                        "schema": {
                            "$ref": "#/definitions/api.createArticleSuccessResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/api/tags": {
            "post": {
                "description": "This endpoint is used to create a new tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Creates a new tag",
                "parameters": [
                    {
                        "description": "Tag Data",
                        "name": "qoute",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createTagRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tag Created Succefully",
                        "schema": {
                            "$ref": "#/definitions/api.createTagSuccessResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errResponseBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.article": {
            "type": "object",
            "properties": {
                "article_text": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.articleRequestBody": {
            "type": "object",
            "properties": {
                "article_text": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "tag_id": {
                    "type": "string"
                }
            }
        },
        "api.createArticleSuccessResponseBody": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.article"
                },
                "message": {}
            }
        },
        "api.createTagRequestBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "api.createTagSuccessResponseBody": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.tag"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.errResponseBody": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "api.tag": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "go-blog API",
	Description:      "Simple http server for creating go-blog and hosting go-blog",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
