// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/api/go-blog": {
            "post": {
                "description": "This endpoint is used to create new go-blog",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "go-blog"
                ],
                "summary": "Creates a new Qoute",
                "parameters": [
                    {
                        "description": "Qoute Data",
                        "name": "qoute",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.qouteRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Qoute Created",
                        "schema": {
                            "$ref": "#/definitions/api.createQouteSuccessResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/api/go-blog/random": {
            "get": {
                "description": "This endpoint is used to return random go-blog",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "go-blog"
                ],
                "summary": "Gets a random qoute from the server",
                "responses": {
                    "200": {
                        "description": "Qoute returned",
                        "schema": {
                            "$ref": "#/definitions/api.createQouteSuccessResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errResponseBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.createQouteSuccessResponseBody": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.qoute"
                },
                "message": {}
            }
        },
        "api.errResponseBody": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "api.qoute": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "qoute_text": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.qouteRequestBody": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "qoute_text": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "go-blog API",
	Description:      "Simple http server for creating go-blog and hosting go-blog",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
