definitions:
  api.article:
    properties:
      article_text:
        type: string
      author:
        type: string
      created_at:
        type: string
      id:
        type: string
      published_at:
        type: string
      updated_at:
        type: string
    type: object
  api.articleRequestBody:
    properties:
      article_text:
        type: string
      author:
        type: string
      tag_id:
        type: string
    type: object
  api.createArticleSuccessResponseBody:
    properties:
      data:
        $ref: '#/definitions/api.article'
      message: {}
    type: object
  api.createTagRequestBody:
    properties:
      name:
        type: string
    type: object
  api.createTagSuccessResponseBody:
    properties:
      data:
        $ref: '#/definitions/api.tag'
      message:
        type: string
    type: object
  api.errResponseBody:
    properties:
      data: {}
      message:
        type: string
    type: object
  api.tag:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: Simple http server for creating go-blog and hosting go-blog
  title: go-blog API
  version: "1.0"
paths:
  /v1/api/articles:
    post:
      consumes:
      - application/json
      description: This endpoint is used to create a new article
      parameters:
      - description: Article Data
        in: body
        name: qoute
        required: true
        schema:
          $ref: '#/definitions/api.articleRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Article Created Succefully
          schema:
            $ref: '#/definitions/api.createArticleSuccessResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errResponseBody'
      summary: Creates a new blog article
      tags:
      - articles
  /v1/api/tags:
    post:
      consumes:
      - application/json
      description: This endpoint is used to create a new tag
      parameters:
      - description: Tag Data
        in: body
        name: qoute
        required: true
        schema:
          $ref: '#/definitions/api.createTagRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Tag Created Succefully
          schema:
            $ref: '#/definitions/api.createTagSuccessResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errResponseBody'
      summary: Creates a new tag
      tags:
      - tags
swagger: "2.0"
